from __future__ import annotations

import sqlite3
from pathlib import Path

import pytest
import yaml

from src.main import main


def _write_review_yaml(path: Path) -> None:
    payload = {
        "research_question": "How does automated tutoring impact learning outcomes?",
        "review_type": "systematic",
        "pico": {
            "population": "students",
            "intervention": "ai tutor",
            "comparison": "traditional instruction",
            "outcome": "learning outcomes",
        },
        "keywords": ["ai tutor", "education"],
        "domain": "education",
        "scope": "health sciences",
        "inclusion_criteria": ["peer reviewed studies"],
        "exclusion_criteria": ["opinion pieces"],
        "date_range_start": 2015,
        "date_range_end": 2026,
        "target_databases": ["openalex"],
        "protocol": {
            "registered": True,
            "registration_number": "CRD42025678901",
            "registration_date": "2026-01-15",
        },
        "target_sections": ["abstract", "methods", "results"],
    }
    path.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")


def _write_settings_yaml(path: Path) -> None:
    payload = {
        "agents": {
            "screening_reviewer_a": {"model": "google:gemini-2.5-flash-lite", "temperature": 0.1},
            "screening_reviewer_b": {"model": "google:gemini-2.5-flash-lite", "temperature": 0.3},
            "screening_adjudicator": {"model": "google:gemini-2.5-pro", "temperature": 0.2},
            "quality_assessment": {"model": "google:gemini-2.5-pro", "temperature": 0.1},
            "search": {"model": "google:gemini-2.5-flash", "temperature": 0.1},
            "extraction": {"model": "google:gemini-2.5-pro", "temperature": 0.1},
            "writing": {"model": "google:gemini-2.5-pro", "temperature": 0.2},
        },
        # warning mode so search_volume_gate doesn't hard-fail on 0 papers from mocked search.
        "gates": {"profile": "warning"},
        "rag": {
            "embed_model": "sentence-transformers:lightonai/DenseOn",
            "use_hyde": False,
            "rerank": False,
        },
    }
    path.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")


def _patch_empty_search_connectors(monkeypatch: pytest.MonkeyPatch) -> None:
    def _fake_build_connectors(workflow_id: str, target_databases: list[str]) -> tuple[list, dict[str, str]]:
        _ = (workflow_id, target_databases)
        return [], {}

    monkeypatch.setattr(
        "src.orchestration.helpers.search_connectors.build_connectors",
        _fake_build_connectors,
    )
    monkeypatch.setattr(
        "src.orchestration.runners.search_runner._build_connectors",
        _fake_build_connectors,
    )
    monkeypatch.setattr(
        "src.orchestration.workflow._build_connectors",
        _fake_build_connectors,
    )


def test_run_executes_single_path_orchestrator(tmp_path, monkeypatch: pytest.MonkeyPatch) -> None:
    _patch_empty_search_connectors(monkeypatch)
    review_path = tmp_path / "review.yaml"
    settings_path = tmp_path / "settings.yaml"
    run_root = tmp_path / "runs"
    _write_review_yaml(review_path)
    _write_settings_yaml(settings_path)

    code = main(
        [
            "run",
            "--config",
            str(review_path),
            "--settings",
            str(settings_path),
            "--run-root",
            str(run_root),
        ]
    )
    assert code == 0

    run_summaries = list(run_root.rglob("run_summary.json"))
    assert run_summaries, "run_summary.json should be generated by run command"
    run_dir = run_summaries[0].parent
    runtime_db = run_dir / "runtime.db"
    assert runtime_db.exists()
    app_log = run_dir / "app.jsonl"
    assert app_log.exists(), "app.jsonl should be generated for structured logging"
    conn = sqlite3.connect(runtime_db)
    try:
        cursor = conn.execute("SELECT phase FROM checkpoints")
        phases = {str(row[0]) for row in cursor.fetchall()}
    finally:
        conn.close()
    assert {
        "phase_1_prospero_gate",
        "phase_2_search",
        "phase_3_screening",
        "phase_4_extraction_quality",
        "phase_5_synthesis",
        "phase_6_writing",
    }.issubset(phases)
